from django.conf import settings

FREELANCER = "Freelancer"
TEAM = "Team"
AGENCY = "Agency"
ENTERPRISE = "Enterprise"
FREE = "Free"

PLAN_UNDEFINED = "undefined"
PLAN_FREE = "beepro_free"
PLAN_FREELANCER_ANNUAL = "beepro_freelancer_annual"
PLAN_FREELANCER = "beepro_freelancer"
PLAN_TEAM_ANNUAL = "beepro_team_annual"
PLAN_TEAM = "beepro_team"
PLAN_AGENCY_ANNUAL = "beepro_agency_annual"
PLAN_AGENCY = "beepro_agency"
PLAN_ENTERPRISE_ANNUAL = "beepro_enterprise_annual"
PLAN_ENTERPRISE = "beepro_enterprise"

PLAN_NAMES_MAP = {
    PLAN_FREE: FREE,
    PLAN_FREELANCER: FREELANCER,
    PLAN_FREELANCER_ANNUAL: FREELANCER,
    PLAN_TEAM: TEAM,
    PLAN_TEAM_ANNUAL: TEAM,
    PLAN_AGENCY: AGENCY,
    PLAN_AGENCY_ANNUAL: AGENCY,
    PLAN_ENTERPRISE: ENTERPRISE,
    PLAN_ENTERPRISE_ANNUAL: ENTERPRISE,
}

UNLIMITED = -1


LEGACY_PLANS = (AGENCY, FREELANCER)


RESTRICTIONS = {
    "Brand": {FREE: 1, FREELANCER: 1, TEAM: 1, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "Project": {FREE: 0, FREELANCER: 3, TEAM: UNLIMITED, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "Message": {FREE: 10, FREELANCER: UNLIMITED, TEAM: UNLIMITED, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "Template": {FREE: 3, FREELANCER: UNLIMITED, TEAM: UNLIMITED, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "RowCategory": {FREE: 1, FREELANCER: UNLIMITED, TEAM: UNLIMITED, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "SavedRow": {FREE: 2, FREELANCER: UNLIMITED, TEAM: UNLIMITED, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "IncludedSeats": {FREE: 1, FREELANCER: 1, TEAM: 2, AGENCY: 4, ENTERPRISE: 10},
    "IncludedTrafficMb": {
        FREE: 20 * 1024,
        FREELANCER: 50 * 1024,
        TEAM: 250 * 1024,
        AGENCY: 500 * 1024,
        ENTERPRISE: 2000 * 1024,
    },
    "MaxNoBillingSeat": {FREE: UNLIMITED, FREELANCER: 0, TEAM: 4, AGENCY: 20, ENTERPRISE: 0},
    "HistoryRestorableVersions": {FREE: 2, FREELANCER: 0, TEAM: UNLIMITED, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "HistoryVisibleVersions": {FREE: 10, FREELANCER: 0, TEAM: UNLIMITED, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "ExportMessage": {FREE: 6, FREELANCER: UNLIMITED, TEAM: UNLIMITED, AGENCY: UNLIMITED, ENTERPRISE: UNLIMITED},
    "AiTokens": {FREE: 100000, FREELANCER: 100000, TEAM: 100000, AGENCY: 100000, ENTERPRISE: 100000},
    # Real AiTokens limits disabled until BEEPRO-4445 is completed
    # "AiTokens": {FREE: 4000, FREELANCER: 4000, TEAM: 16667, AGENCY: 16667, ENTERPRISE: 60000},
}
