from .base import *  # noqa

# BEEPRO PROXY
BEEPRO_PROXY_API_KEY = "fake_key"
BEEPRO_PROXY_URL = "https://pre-bee-beepro-proxy.getbee.info"

# Toplyne
TOPLYNE_API_URL = ""
TOPLYNE_API_TOKEN = ""

TDV_API_URL = ""
TDV_USER = "test_user"
TDV_PASSWORD = "test_password"


# PARTNERSTACK
PARTNERSTACK_CUSTOMER_URL = ""
PARTNERSTACK_USER = ""
PARTNERSTACK_PASSWORD = ""
PARTNERSTACK_IGNORE_ERRORS = True

# EHAWK
EHAWK_API_URL = ""
EHAWK_FEED_API_URL = ""
EHAWK_APY_KEY = ""
EHAWK_PASSING_LIMIT_SCORE = -50
EHAWK_PASSING_BLOCK_SCORE = -100
EHAWK_ENABLED = False
EHAWK_ENABLE_BLOCK_SCORE = False

# ZAPIER
ZAPIER_BASE_URL = ""
ZAPIER_SUBSCRIPTION_CRUD_ZAP_PATH = ""  # Testing Path
ZAPIER_NEW_USER_ZAP_PATH = ""  # Testing Path
ZAPIER_NEW_TRIAL_ZAP_PATH = ""  # Testing Path
ZAPIER_CALLS_ENABLED = True
OLD_ZAPIER_BASE_URL = ""

# Billing Portal
BILLING_PORTAL_API_KEY = ""
BILLING_PORTAL_MAX_PREVIEW_PARALLEL_CALLS = 1

BEE_EAR_BASE_URL = ""
BEE_EAR_APPLICATION = ""

# Data Service
DATA_SERVICE_URL = ""
DATA_SERVICE_API_KEY = ""
DATA_SERVICE_CALLS_ENABLED = True

# Hook Service
HOOK_SERVICE_BASE_URL = ""
HOOK_SERVICE_CALLS_ENABLED = True
